version: '3.2'

services:
  hugo:
    image: klakegg/hugo:0.111.3-ext-debian
    volumes:
      - "./src:/src"
    ports:
      - "1313:1313"
    environment:
      - VIRTUAL_HOST=psql.loc
    command: server
    labels:
      com.dnsdock.alias: psql.loc
